"""M5: int8 weight quantization, proven by MEASUREMENT WITH CONTROL.

Discipline shift vs. M0: there is no analytic tolerance derivation here.
Float-accumulation error has a formula (sqrt(K)*eps per reduction); the impact
of quantization on perplexity does not. So the quality claim is RELATIVE — the
chosen scheme must sit far closer to the float64 baseline than a deliberately
coarser control scheme does — instead of an absolute threshold invented to look
reasonable.

===========================================================================
PASSO 1 — measured weight distribution of THIS checkpoint (not literature)
===========================================================================

All numbers from fixtures/personacore_parity.npz via load_weights (f64):

  category                     min..max         mean      std     skew
  wte.weight  (8192, 384)   -0.376..0.400    -0.00236   0.0959   -0.036
  wpe.weight  (256, 384)    -0.284..0.323    -0.00003   0.0268    0.020
  attn Linear (6 sampled)   -0.295..0.347    |mean|<5e-5          |skew|<=0.043
  mlp Linear  (4 sampled)   -0.400..0.269    |mean|<2e-4          |skew|<=0.003
  LayerNorm weights          0.208..1.384     0.46..1.07          up to -8.0

  -> Linear + embeddings: symmetric around zero (|skew| <= 0.043, |mean| << std).
     SYMMETRIC quantization justified by measurement; no zero-point needed.
  -> LayerNorm weights: all-positive, mean 0.46-1.07, skew to -8.0 — the ONE
     category that is NOT symmetric around zero. Symmetric int8 would waste half
     its range there. And LN weight+bias is 9,984 params = 0.072% of 13,891,584
     — no memory gain, real stability risk. EXCLUDED, with numbers.
  -> Per-channel |w|max over the input axis (one scale per OUTPUT channel; in
     this engine's (in, out) storage the output channel is the LAST axis):
       q_proj 4.90x, v_proj 2.76x, fc_in 6.17x, fc_out 1.98x, wte 3.64x
     between largest and smallest channel |w|max in the SAME tensor. A single
     per-tensor scale would waste up to log2(6.17) ~ 2.6 bits of the 8 on the
     quietest channel. PER-CHANNEL justified by measurement.
  -> wte is 3,145,728 params = 22.6% of the model (not the ~18% the spec
     guessed) and is tied to the lm_head. QUANTIZED — it is the single biggest
     memory win — but measured SEPARATELY in the perplexity test below (with
     and without), per spec.

Eligible: 36 Linear weights (76.4%) + wte + wpe (23.4%) = 99.8% of params.
Untouched: LayerNorm weight/bias (0.072%) and Linear biases (0.149%), float64.

The perplexity window is `val_windows.npz` :: windows[0] — the first 257-token
window of data/val.bin (start offset 0), generated by the tensorforge alongside
the parity fixture. inputs = window[:-1], targets = window[1:].
"""

import os

import numpy as np
import pytest

from engine.forward import cross_entropy, gpt_forward
from engine.quantize import (
    dequantize_int8,
    dequantize_params,
    is_quantizable,
    quantize_int8,
    quantize_params,
)
from engine.weights import load_weights

_FIXDIR = os.path.join(os.path.dirname(__file__), os.pardir, "fixtures")
FIXTURE = os.path.join(_FIXDIR, "personacore_parity.npz")
VAL_WINDOWS = os.path.join(_FIXDIR, "val_windows.npz")

pytestmark = pytest.mark.skipif(
    not os.path.exists(FIXTURE),
    reason="fixtures/personacore_parity.npz absent — run the tensorforge generator "
    "gen_parity_fixture.py against a trained checkpoint to produce it",
)

N_HEAD = 6


@pytest.fixture(scope="module")
def params():
    return load_weights(FIXTURE)


@pytest.fixture(scope="module")
def ref():
    return np.load(FIXTURE)


def relative_error(got, expected):
    """Same metric as M0: global max abs diff over global max abs reference."""
    return np.abs(got - expected).max() / np.abs(expected).max()


# ---------------------------------------------------------------------------
# 1. round-trip error is bounded by the derived formula
# ---------------------------------------------------------------------------


def test_quantize_dequantize_round_trip_error_bounded(params):
    """Derived bound, written BEFORE measuring:

    A uniform symmetric quantizer with round-to-nearest maps w to
    q = rint(w / s), so |w - q*s| = s * |w/s - rint(w/s)| <= s/2 — half a step.
    Two corrections on top of the ideal s = amax/127:
      * s is STORED as float32, so the s actually used differs from amax/127 by
        at most one f32 ulp (2^-24 relative). If it rounded DOWN, w/s can reach
        127/(1 - 2^-24) ~ 127.0000076, which still rints to 127 — but the
        clipped value 127*s then misses amax by up to amax * 2^-24.
      * therefore: |w - q*s| <= s/2 + amax * 2^-24 = s * (1/2 + 127 * 2^-24).
    The assertion uses s * (0.5 + 1e-4), comfortably above 127 * 2^-24 ~ 7.6e-6.

    And the formula must MATCH the measurement, not merely bound it: over ~10^5
    elements per tensor the worst rounding residual should come close to the
    s/2 ceiling. The lower assertion (>= 0.45 * s) confirms the measured error
    is the predicted half-step, not accidentally 10x smaller (which would mean
    the bound — or the quantizer — is not what we think it is).
    """
    for name in ["blocks.0.attn.q_proj.weight", "blocks.0.mlp.fc_in.weight", "wte.weight"]:
        w = params[name]
        q, s = quantize_int8(w)
        assert q.dtype == np.int8 and s.dtype == np.float32
        dq = dequantize_int8(q, s)
        ratio = (np.abs(dq - w) / s.astype(np.float64)).max()
        assert ratio <= 0.5 + 1e-4, f"{name}: max err {ratio:.6f} * s exceeds the derived bound"
        assert ratio >= 0.45, f"{name}: max err {ratio:.6f} * s — far below s/2, formula mismatch"


# ---------------------------------------------------------------------------
# 2. the scale comes from the REAL max-abs, not a biased estimate
# ---------------------------------------------------------------------------


def test_quantization_scale_uses_max_abs_not_a_biased_estimate(params):
    """scale * 127 must reproduce |w|max exactly (to f32 rounding). A mean- or
    percentile-based scale would sit far below it — on q_proj the channel means
    are ~12x smaller than the channel maxes — and every weight above the biased
    ceiling would silently clip."""
    w = params["blocks.0.attn.q_proj.weight"]

    q, s = quantize_int8(w)  # per-channel: one scale per output column
    amax = np.abs(w).max(axis=0, keepdims=True)
    assert np.allclose(s.astype(np.float64) * 127.0, amax, rtol=1e-6, atol=0)
    # the loudest weight of every channel must land ON the top code, not below it
    assert (np.abs(q).max(axis=0) == 127).all()

    q, s = quantize_int8(w, per_channel=False)  # one scale for the whole tensor
    assert np.allclose(float(s) * 127.0, np.abs(w).max(), rtol=1e-6, atol=0)


# ---------------------------------------------------------------------------
# 3. per-channel is not per-tensor in disguise
# ---------------------------------------------------------------------------


def test_per_channel_scale_differs_across_channels_when_ranges_differ(params):
    """fc_in of block 0 was MEASURED (Passo 1) to have a 6.17x spread between
    its loudest and quietest output channel. The scales must reproduce that
    spread — identical scales would mean the reduction axis silently covers the
    whole tensor."""
    q, s = quantize_int8(params["blocks.0.mlp.fc_in.weight"])
    assert s.shape == (1, 1536), "one scale per OUTPUT channel (last axis of (in, out))"
    spread = float(s.max() / s.min())
    assert np.unique(s).size > 1
    assert spread > 5.0, f"measured channel spread was 6.17x; scales only span {spread:.2f}x"


# ---------------------------------------------------------------------------
# 4. LayerNorm and biases are never quantized
# ---------------------------------------------------------------------------


def test_layernorm_and_biases_are_never_quantized(params):
    qp = quantize_params(params)
    assert qp.keys() == params.keys()

    n_quantized = 0
    for name, orig in params.items():
        if ".ln_" in name or name.startswith("ln_f") or name.endswith(".bias"):
            assert isinstance(qp[name], np.ndarray), f"{name} must stay a plain array"
            assert qp[name].dtype == np.float64
            assert np.array_equal(qp[name], orig), f"{name} must be bit-identical"
            assert not is_quantizable(name)
        else:
            q, s = qp[name]
            assert q.dtype == np.int8 and s.dtype == np.float32, name
            n_quantized += 1
    # 6 layers x (4 attn + 2 mlp) Linear weights + wte + wpe
    assert n_quantized == 38


# ---------------------------------------------------------------------------
# 5. the quantized forward does not diverge catastrophically
# ---------------------------------------------------------------------------


def test_quantized_forward_matches_full_precision_within_derived_bound(params, ref):
    """NOT an M0-style tolerance: the error here is BY DESIGN (the weights were
    deliberately coarsened), not floating-point accumulation. This test only
    rules out catastrophic divergence — the real quality gate is the perplexity
    test below. The measured value is reported in the assertion message."""
    dq = dequantize_params(quantize_params(params))
    got = gpt_forward(ref["input_x"], dq, n_head=N_HEAD)
    expected = gpt_forward(ref["input_x"], params, n_head=N_HEAD)
    rel = relative_error(got, expected)
    assert rel < 1e-1, f"quantized forward diverges: relative error {rel:.3e}"


# ---------------------------------------------------------------------------
# 6. THE CENTRAL TEST: perplexity baseline vs int8 vs a deliberately coarse control
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    not os.path.exists(VAL_WINDOWS),
    reason="fixtures/val_windows.npz absent — generated by the tensorforge alongside "
    "the parity fixture",
)
def test_perplexity_baseline_vs_quantized_vs_deliberately_coarse(params):
    """Window: val_windows.npz windows[0] — first 257 tokens of val.bin (start
    offset 0, per its `starts` array). inputs = window[:-1], targets = window[1:].

    Control scheme: SIMULATED INT4 — same symmetric per-channel quantizer, range
    [-7, 7] instead of [-127, 127], applied to the same eligible tensors. Chosen
    over per-tensor int8 as the control because Passo 1 measured only a 2-6x
    channel spread, so per-tensor int8 could land close to per-channel and make
    the contrast unreadable; 16x fewer levels cannot.

    The claim is RELATIVE: int8 must sit at least 2x closer to the baseline than
    the int4 control does. If they came out similar it would mean a bug in the
    per-channel implementation, not that int8 is bad. The wte contribution is
    also measured separately (quantized vs kept float), per the Passo 2 decision
    to quantize the tied embedding."""
    window = np.load(VAL_WINDOWS)["windows"][0]
    x, targets = window[:-1], window[1:]

    def perplexity(p):
        return float(np.exp(cross_entropy(gpt_forward(x, p, n_head=N_HEAD), targets)))

    def int4_params(p):
        out = {}
        for name, w in p.items():
            if is_quantizable(name):
                s = np.abs(w).max(axis=tuple(range(w.ndim - 1)), keepdims=True) / 7.0
                out[name] = np.clip(np.rint(w / s), -7, 7) * s
            else:
                out[name] = w
        return out

    baseline = perplexity(params)
    int8 = perplexity(dequantize_params(quantize_params(params)))
    int8_no_wte = perplexity(dequantize_params(quantize_params(params, include_embeddings=False)))
    int4 = perplexity(int4_params(params))

    report = (
        f"ppl baseline={baseline:.6f}  int8={int8:.6f}  "
        f"int8(sem wte/wpe)={int8_no_wte:.6f}  int4-control={int4:.6f}"
    )
    assert abs(int8 - baseline) * 2 < abs(int4 - baseline), report
    # the control must actually be coarse — a control indistinguishable from the
    # baseline controls nothing
    assert abs(int4 - baseline) > abs(int8 - baseline), report


# ---------------------------------------------------------------------------
# 7. the storage is actually smaller, measured in bytes
# ---------------------------------------------------------------------------


def test_int8_storage_is_smaller_than_original(params):
    """Measured, not estimated: nbytes of every q_weight (int8) plus its scales
    (float32, one per channel) against the same tensors in engine float64.
    int8 vs f64 is 8x on the payload; the scales cost one f32 per output
    channel, pulling the measured ratio slightly under 8."""
    qp = quantize_params(params)
    orig = sum(v.nbytes for k, v in params.items() if is_quantizable(k))
    quant = sum(q.nbytes + s.nbytes for v in qp.values() if isinstance(v, tuple) for q, s in [v])
    ratio = orig / quant
    assert ratio > 7.5, f"measured compression {ratio:.3f}x"
    assert ratio < 8.0, "scales are not free — exactly 8x would mean they were not stored"
